---
- hosts: earth
  tasks:
  - name: Log into Docker Registry Dan
    community.general.docker_login:
          registry: registry.digitalocean.com
          username: "{{ digital_ocean_token }}"
          password: "{{ digital_ocean_token }}"
